### ISSUE TITLE
Request for help to understand prepareApks in SampleAutomaticAnalysis.conf

### ISSUE THREAD

**Issue by Tushit123** [AndroidHooker/hooker#10]
After running install.sh which internally calls "ant debug" which generates "ImportContacts-debug.apk"
inside bin folder of "APK-contactGenerator" dir. And sampleAutomaticAnalysis.conf file has "prepareApks=../tools/APK-contactGenerator/com.amossys.hooker.generatecontacts.ImportContacts.apk" variable defined.
#1 : where can i find "com.amossys.hooker.generatecontacts.ImportContacts.apk"?
#2: if user has to define that variable , what should i define? I tried defining " ImportContacts-debug.apk" as "prepareApks" variable but code crashes. Can you please help? Error for #2

Starting: Intent { cmp=/.ImportContacts-debug }
[MainProcess/MainThread/INFO] 88772: Analyzing directory: ../tools/sampleApps/
[MainProcess/MainThread/DEBUG] 88772: All APKs have been pushed to the analyzing queue, sleeping 5 secs...
Error type 3
Error: Activity class {/.ImportContacts-debug} does not exist.
[MainProcess/MainThread/INFO] 93776: Analyzing directory: ../tools/sampleApps/

**Comment by Tibap** [comment]
You have to define prepareApks to your generated ImportContacts apk. If you did not change anything, this should be: "../tools/APK-contactGenerator/bin/ImportContacts-debug.apk".

**Comment by Tushit123** [comment]
I tried with ImportContacts-debug.apk also but it is giving me another error saying that  ImportContacts-debug class is not available. 
I found ImportContacts class but not ImportContacts-debug.

**Comment by Tibap** [comment]
You have to rename ImportContacts-debug.apk into ImportContacts.apk and set the corresponding path into your configuration file.

**Comment by Tushit123** [comment]
I have one another question.
I got the message "The event information of experiment '99ab8cf3c7e126b7600931860dfe16f9' has successfuly been inserted into ES cluster."

Now, How can I see the result in cluster. Will it create any log file?
