### ISSUE TITLE
how to see result log saved data in Elasticsearch Cluster?

### ISSUE THREAD

**Issue by Tushit123** [AndroidHooker/hooker#11]
After successfully run hooker_xp.py, I got "The event information of experiment '99ab8cf3c7e126b7600931860dfe16f9' has successfuly been inserted into ES cluster." message.

Now, how can I see these cluster? Does t creates any log file?

**Comment by Tibap** [comment]
You have to access your ES database. 2 choices:
- either install the HEAD plugin (see the README file) 
- or install Kibana, import the example dashboard, and check results

You can watch this [video](https://vimeo.com/153103204) to see an example of how a normal XP looks like.

**Comment by Tushit123** [comment]
Can I get requested permissions list in any file?
