### ISSUE TITLE
Get Permissions list

### ISSUE THREAD

**Issue by Tushit123** [AndroidHooker/hooker#12]
Using Android Hooker, Is it possible to get requested permissions list in one file?

**Comment by Tibap** [comment]
Hooker is using Androguard in order to statically analyze the application's permissions. This is done before the dynamic analysis, and you can get the result either in the terminal during the experiment or in the ElasticSearch database.

**Comment by Tushit123** [comment]
Hello,

I need your help to do more with Android Hooker.

I would like to detect malicious applications using API call and
permissions.

According to one research paper, "Feature generator, carries out feature
extraction, which includes permission features extracted from
AndroidManifest and API call features extracted from class files. As a
result of this this process, each App is represented as a single instance
with binary permission and API call features,
and a class label indicates whether the App is a benign or a malware".

Can you guide be what can I do next?

Thanks,
- Arpita
