### ISSUE TITLE
Elastic search and Kibana get data from which file

### ISSUE THREAD

**Issue by Tushit123** [AndroidHooker/hooker#13]
@Tibap 
I would like to know from which file you get all data into Elasticsearch head and Kibana. 
I searched but get binary files.

**Comment by Tibap** [comment]
Hooker_xp will directly send events to your ES database if you specify an IP in the configuration file. However, if you cannot connect your Android device to your ES database, you'll have to store events locally (see configuration file), extract the corresponding file, and then replay these events in your ES database.
