### ISSUE TITLE
events.logs not found

### ISSUE THREAD

**Issue by Tushit123** [AndroidHooker/hooker#14]
I would like to know where events.logs file is stored.

**Comment by Tibap** [comment]
The file is stored in /sdcard/hooker/ directory on the Android device. When you run an automatic analysis, the file should be pulled in the temporary path you define in the configuration file. If you run a manual analysis, you can use `adb` to extract the file from the Android device.

**Comment by Tushit123** [comment]
Thank you so much Tibap. It really helped. :)
