### ISSUE TITLE
Help to get APK name also in events.logs

### ISSUE THREAD

**Issue by Tushit123** [AndroidHooker/hooker#15]
Hello,
I'm getting package-name, method-name, and class-name in events.logs file. 
But I'm not getting apk-name in it. 

Can somebody help me?

**Comment by Tibap** [comment]
I'm not sure why you want the APK name since it can be modify by anyone. Package name is what identify the best your APK.
Also, please consider writing a mail to android-hooker@amossys.fr if you're not having any bug.
