### ISSUE TITLE
Kibana Dashboard 

### ISSUE THREAD

**Issue by ghost** [AndroidHooker/hooker#16]
Hello,
The data collected into ES, for some reason is not loaded into Kibana.
Importing the dashboard (tools/kibana-dashboard/kibana-export.json) as described in the section "Start ElasticSearch and Kibana" always show the message 

> "Saved Objects: Could not locate that index-pattern (id: hooker_test)" 
> In the top of Kibana Settings page

May this warning be the problem?

This is just a piece of data seen under ES (http://localhost:9200/_plugin/head/):

```
{

    "_index": "hooker_test",
    "_type": "static",
    "_id": "AVPIqrs0HrDCae4vI9ZR",
    "_score": 1,
    "_source": {
        "Android Version Code": "57",
        "PackageName": "com.code.spirity",
        "Main Activity": "com.code.spirity.ui.tour.SplashActivity",
        "Libraries": [ ],
        "Filename": "/home/wagner/droid/analysis/new/base.apk",
        "Activities": [
            {
                "Activity": "com.code.spirity.ui.tour.SplashActivity"
            }
            ,
            {
                "Activity": "com.code.spirity.ui.tour.TourActivity"
            }
            ,
...
```

I mean, it seems that everything is ok with Hooker execution and data collection, the problem is apparently with Kibana's Dashboard.
Do you have a clue on how to solve that?
Thanks in advance.

**Comment by Tibap** [comment]
Importing a new dashboard in Kibana is a bit tricky. Please try these steps:
- check that you have Hooker events in ES database
- go to 'Settings > Indices' and search for the hooker_test index name (see first screenshot below)
- go to 'Objects' and 'Import' the Kibana dashboard from the repo. If all went well, you should have something like in the second screenshot.

Hope this helps!
![kibana-configure-1](https://cloud.githubusercontent.com/assets/3305171/14168377/52b091ba-f722-11e5-8631-8ebe196d2c2a.png)
![kibana-configure-2](https://cloud.githubusercontent.com/assets/3305171/14168402/7981fee6-f722-11e5-9c1f-1c8e6093ad2d.png)

**Comment by ghost** [comment]
It worked! Thank you very much Tibap.
I know nothing about Kibana and didn't realized that the index it was talking about was one of its configuration tricks :)

Best regards,
