### ISSUE TITLE
Error happened when the "experiment"  inserting into ES cluster

### ISSUE THREAD

**Issue by yangximi** [AndroidHooker/hooker#17]
Hello:
when I  run `python hooker_xp.py -c myAnalysis.conf`, the Error happened as follow :

[MainProcess/Reporter.py:69/INFO] 101: No APK found associated with IDXP 4ca6b8a3e75b46c7b3acb747756a5792
[MainProcess/Es.py:359/DEBUG] 111: The APK '/home/ximi/DroidBox_4.1.1/MaliciousTest_For4.0.apk' has successfuly been inserted into ES cluster.
[MainProcess/Reporter.py:74/INFO] 112: APK /home/ximi/DroidBox_4.1.1/MaliciousTest_For4.0.apk with ID e5777ad1-f8d3-44d9-a3ef-2294c5a5e409 has been assiocated to IDXP in ES cluster
[MainProcess/Es.py:113/DEBUG] 122: The experiment '4ca6b8a3e75b46c7b3acb747756a5792' has successfuly been inserted into ES cluster.
### --------------------------------------Error at here--------------------------------------

[MainProcess/hooker_xp.py:70/ERROR] 124: Traceback (most recent call last):
  File "hooker_xp.py", line 67, in <module>
    main()
  File "hooker_xp.py", line 61, in main
    analysis.start()
  File "/home/ximi/Dynamic_Analysis_of_APP/hooker-master/hooker_xp/hooker_xp/ManualAnalysis.py", line 83, in start
    Analysis.reportEvent(self.reporter, idXp, "Analysis", "Executing static analysis on {0}".format(analyzedAPKFile))
  File "/home/ximi/Dynamic_Analysis_of_APP/hooker-master/hooker_xp/hooker_xp/analysis/Analysis.py", line 85, in reportEvent
    reporter.reportEvent(idXp, sourceEvent, actionEvent, paramsEvent)
  File "/home/ximi/Dynamic_Analysis_of_APP/hooker-master/hooker_xp/hooker_xp/report/Reporter.py", line 92, in reportEvent
    self.es.insertExperimentSteps(idXp, relTime, emulator=sourceEvent, description=actionEvent)
  File "build/bdist.linux-x86_64/egg/hooker_common/elasticsearch/Es.py", line 131, in insertExperimentSteps
    raise Exception("Experiment with ID '{0}' doesn't exists, create it before inserting a static event.".format(idXp))
Exception: Experiment with ID '4ca6b8a3e75b46c7b3acb747756a5792' doesn't exists, create it before inserting a static event.

---

As I saw the "Es.py" script, It seems that it can't find the Experiment in the second time.
I wonder if you can  help me
Thanks in advance

**Comment by Tibap** [comment]
Hi @yangximi,
Can you try to change your ElasticSearch index (in the configuration filen the parameter elasticsearch_index) to see if you have a similar result?
If that doesn't help, can you give the complete output logs? Moreover, more details on your experiment environment would help: what distribution do you use? Which version? What version of ElasticSearch do you have?
