### ISSUE TITLE
In SharedPreferencesHooker.java, " android.content.SharedPreferences.Editor" not works!

### ISSUE THREAD

**Issue by guanchao** [AndroidHooker/hooker#20]
In SharedPreferencesHooker.java, it was ussless to hook android.content.SharedPreferences.Editor. Because Editor is interface, which can not be hooked. 
So we shoud hook it's implementation, which is android.app.SharedPreferencesImpl$EditorImpl, and it works!

**Comment by Tibap** [comment]
Thanks @guanchao ! Please submit a pull request if you have time. Otherwise, I'll try to push this minor fix in the next weeks.

**Comment by guanchao** [comment]
@Tibap. OK. I had submitted.

**Comment by Tibap** [comment]
Merged. Thanks for your feedback!
