### ISSUE TITLE
AVD Snapshot Unresponsive/Offline

### ISSUE THREAD

**Issue by 0xdeadbeefJERKY** [AndroidHooker/hooker#3]
After creating and prepping the Android AVD, attempting to launch the AVD from the saved snapshot results in a frozen AVD. The home screen loads fine, but the device is seen as ofline and I'm unable to interact with the screen within the AVD.

I've scoured forums and Google for potential solutions, but have found none.

**Comment by Tibap** [comment]
With the little information you just gave, it sounds like a Substrate issue... However, we need a lot more information to help you. Can you provide these details :
- the android SDK version
- the emulator architecture and physical device details
- the substrate version
- how you rooted your device
- what version of Hooker you're using.

**Comment by TheBananaStand** [comment]
SDK -

**Comment by 0xdeadbeefJERKY** [comment]
SDK - Exact specifications listed for the AVD in the Wiki (4.2.1 - API 16)
Substrate - Version included in Hooker git
Rooted emulator:
`
adb wait-for-device
adb remount
adb push su /system/bin
adb shell chmod 6755 /system/bin/su
adb shell rm /system/xbin/su
adb shell ln -s /system/bin/su /system/xbin/su
`
Most recent version of Hooker available via git.

I've followed the instructions to a T.

**Comment by 0xdeadbeefJERKY** [comment]
The AVD operates correctly without any issues when executing a soft reset via Substrate. However, when I close the emulator and attempt to launch the AVD from the snapshot, it launches to the home screen and freezes.

**Comment by gbossert** [comment]
Are you certain the emulator freezes ? 
Can you try to restore a snapshot of a fresh and clean AVD (not rooted, without Substrate) and wait +/- 5 minutes before stimulating it ? [0]

[0] http://code.google.com/p/android/issues/detail?id=77283

**Comment by Ratibhan** [comment]
cd hooker_xp && python hooker_xp.py -c /home/ratibhan/hooker-master/hooker_xp/sampleAutomaticAnalysis.conf 

I have completed all steps, but during execution last command given in README.MD, i got following error, Please tell me the way to resolve it?

ERRROR: No module named colorama

Updated : Dedicated ticket opened here  - https://github.com/AndroidHooker/hooker/issues/4

**Comment by Tibap** [comment]
Dedicated ticket opened here  - https://github.com/AndroidHooker/hooker/issues/4
